### ISSUE TITLE
Getting started with aZ3

### ISSUE THREAD

**Issue by nolleryc** [qsphan/aZ3#1]
Hi all,

I'm trying to get started with aZ3 with a simple example. Here the content of the smtlib2 input file:

```
(set-option :produce-models true)
(set-logic QF_LIA)
(declare-fun constraint1 () Bool)
(declare-fun constraint2 () Bool)
(declare-fun x () Int)
(assert (= constraint1 (> x 0)))
(assert (= constraint2 (< x 5)))
(assert (and constraint1 constraint2))
(check-allsat (constraint1 constraint2))
(allsat-relevant x)
```

I use the BlockingClause method to get the model count for the variable x. I expected that the solver results with the model count 4 (x=1, 2, 3, 4). But I get the following output:

```
BlockingClause Solver
( 
 (  (x 1 )  (constraint1 true )  (constraint2 true )  )

) 

There are 1 models
Elapsed time is 14 ms
```

Am I doing something wrong, or does the solver only handles the propagated boolean expressions?

Thanks,
Yannic

**Comment by qsphan** [comment]
Hi Yannic,

aZ3 only counts the model with respect to a set of Boolean variables. In your example, this set is (constraint1, constraint2), and since you have an assertion that both of them must be true, there is only one model.

The idea is that if you have an SMT formula, it can be in any first-order theory, e.g. linear integer, bit vector, list and so on. The number of model is often infinite, and hence impossible to count. But if you only care about a particular set of Boolean variables in the formula, e.g. in the examples in my paper, then the tool can count the number of models wrt this set.

If you restrict your problem to linear inequalities as in your example, I would suggest to use Latte:
https://www.math.ucdavis.edu/~latte/

Best wishes,
Sang

**Comment by nolleryc** [comment]
Hi Sang,

thanks for your explanations.

Cheers,
Yannic
